---
# tasks file for kubespray

- name: Install required system packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:  
    - python3-dev
    - python3-virtualenv
    - python3-pip
    - virtualenv

- name: Clone repo Kubespray
  ansible.builtin.git:
    repo: "https://github.com/kubernetes-sigs/kubespray.git"
    dest: "{{ path_kubespray }}"
    version: release-2.23

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: "{{ path_kubespray }}/requirements.txt"
    virtualenv: "{{ path_kubespray }}/venv"

- name: Create folder mycluster kubespray
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: '{{ path_cluster_k8s }}/{{ name_cluster }}'
    owner: root
    group: root
    remote_src: yes
  with_fileglob:
    - '{{ path_smple }}'

- name: Copy inventpry file on kubespray
  ansible.builtin.copy:
    src: '{{ path_local_inventory }}/inventory.ini'
    dest: '{{ path_remove_inventory }}/inventory.ini'
    owner: root
    group: root
    