apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdjango
  labels:
    app.kubernetes.io/name: appdjango
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: appdjango
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: appdjango
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: appdjango-deploy
          image: testmaxdev/django-postgresql-image:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: db_name
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pg:5432/$(POSTGRES_DB)
