apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  labels:
    app.kubernetes.io/name: appdjango
    app.kubernetes.io/component: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: appdjango
      app.kubernetes.io/component: pg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: appdjango
        app.kubernetes.io/component: pg
    spec:
      containers:
        - name: pg-deploy
          image: postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: pg
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: db_name
      #     volumeMounts:
      #       - mountPath: /var/lib/postgresql/data
      #         name: postgres-volume-mount
      # volumes:
      #   - name: postgres-volume-mount
      #     persistentVolumeClaim:
      #       claimName: postgres-pv-claim
