apiVersion: v1
kind: Pod
metadata:
  name: pg
spec:
  containers:
    - name: pg-pod
      image: postgres:14
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432
          name: pg
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: db_name
